/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.DetectObject
{
    public class DBinfo : Message
    {
        public override string RosMessageName => "detect_object/DBinfo";

        public int[] FrameB { get; set; }
        public int[] FrameT { get; set; }
        public int[] TimeB { get; set; }
        public int[] TimeT { get; set; }
        public int[] id { get; set; }
        public int[] Xmin { get; set; }
        public int[] Ymin { get; set; }
        public int[] Width { get; set; }
        public int[] Height { get; set; }
        public int[] Depth { get; set; }
        public int[] Yobi { get; set; }
        public int[] YobiYobi { get; set; }
        public int cnt { get; set; }

        public DBinfo()
        {
            this.FrameB = new int[20];
            this.FrameT = new int[20];
            this.TimeB = new int[20];
            this.TimeT = new int[20];
            this.id = new int[20];
            this.Xmin = new int[20];
            this.Ymin = new int[20];
            this.Width = new int[20];
            this.Height = new int[20];
            this.Depth = new int[20];
            this.Yobi = new int[20];
            this.YobiYobi = new int[20];
            this.cnt = 0;
        }

        public DBinfo(int[] FrameB, int[] FrameT, int[] TimeB, int[] TimeT, int[] id, int[] Xmin, int[] Ymin, int[] Width, int[] Height, int[] Depth, int[] Yobi, int[] YobiYobi, int cnt)
        {
            this.FrameB = FrameB;
            this.FrameT = FrameT;
            this.TimeB = TimeB;
            this.TimeT = TimeT;
            this.id = id;
            this.Xmin = Xmin;
            this.Ymin = Ymin;
            this.Width = Width;
            this.Height = Height;
            this.Depth = Depth;
            this.Yobi = Yobi;
            this.YobiYobi = YobiYobi;
            this.cnt = cnt;
        }
    }
}
