/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.CustomTutorials
{
    public class CustomMessage : Message
    {
        public override string RosMessageName => "custom_tutorials_msgs/CustomMessage";

        public string word { get; set; }
        public int number { get; set; }

        public CustomMessage()
        {
            this.word = "";
            this.number = 0;
        }

        public CustomMessage(string word, int number)
        {
            this.word = word;
            this.number = number;
        }
    }
}
